import type { GatewayStarsConfig } from "@/components/gateway/gatewayHomeConfig";

export const techPageStarsConfig: GatewayStarsConfig = {
  radius: 2.2,
  layers: [
    {
      id: "far",
      count: 9000,
      sizeMin: 0.0016,
      sizeMax: 0.003,
      opacityMin: 0.2,
      opacityMax: 0.48,
      palette: ["#f0e8ff", "#d8b8ff", "#c090ff", "#e8d0ff", "#ffffff"],
      rotationX: 24,
      rotationY: 42,
      twinkle: {
        enabled: true,
        fraction: 0.1,
        speedMin: 0.15,
        speedMax: 0.33,
        amplitudeMin: 0.03,
        amplitudeMax: 0.09,
      },
    },
    {
      id: "mid",
      count: 3000,
      sizeMin: 0.003,
      sizeMax: 0.005,
      opacityMin: 0.4,
      opacityMax: 0.88,
      palette: ["#ffffff", "#e8d0ff", "#cc88ff", "#dd66ff", "#f0d0ff"],
      rotationX: 16,
      rotationY: 28,
      twinkle: {
        enabled: true,
        fraction: 0.3,
        speedMin: 0.21,
        speedMax: 0.54,
        amplitudeMin: 0.1,
        amplitudeMax: 0.24,
      },
    },
    {
      id: "accent",
      count: 130,
      sizeMin: 0.006,
      sizeMax: 0.010,
      opacityMin: 0.72,
      opacityMax: 1,
      palette: ["#ffffff", "#eebbff", "#cc44ff", "#dd00ff", "#f0c0ff"],
      rotationX: 14,
      rotationY: 24,
      parallaxStrength: 0.016,
      twinkle: {
        enabled: true,
        fraction: 0.68,
        speedMin: 0.15,
        speedMax: 0.39,
        amplitudeMin: 0.14,
        amplitudeMax: 0.3,
      },
    },
    {
      id: "hero",
      count: 20,
      sizeMin: 0.010,
      sizeMax: 0.015,
      opacityMin: 0.82,
      opacityMax: 1,
      palette: ["#ffffff", "#f0d8ff", "#cc44ff", "#ee00ff"],
      rotationX: 12,
      rotationY: 20,
      haloScale: 3.6,
      haloOpacity: 0.24,
      parallaxStrength: 0.028,
      twinkle: {
        enabled: true,
        fraction: 1,
        speedMin: 0.105,
        speedMax: 0.3,
        amplitudeMin: 0.2,
        amplitudeMax: 0.42,
      },
    },
  ],
  performance: {
    maxDpr: 1.5,
    mobileScale: 0.45,
    reducedMotionDisableTwinkle: true,
  },
  distribution: {
    diagonalBias: 0.22,
    diagonalWidth: 0.28,
    diagonalOffset: 0.04,
    secondaryDiagonalBias: 0.1,
    secondaryDiagonalWidth: 0.36,
    secondaryDiagonalOffset: -0.16,
  },
};
